# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'BCEXRate' do
    pod 'Charts'
end

target 'BCEXRateTests' do

end

target 'BCEXRateUITests' do

end

